### ISSUE TITLE
macos版本点击无反应

### ISSUE THREAD

**Issue by ColeHou** [1c7/translate-subtitle-file#1]
点击无反应，好像都点击不下去，之前好好的

**Comment by 1c7** [comment]
请问开了翻墙吗？没开的话要开。
这个工具用到了谷歌翻译。

**Comment by ColeHou** [comment]
开了的，早上又好了，有点奇怪，昨天我开了上油管没有问题

**Comment by 1c7** [comment]
@ColeHou 这样。那既然现在没问题了，我就把 issue 关掉了。如果还碰到问题。可以描述下出问题的具体情况。然后 reopen 这个 issue。
