### ISSUE TITLE
同一文件夹下，连续翻译多个字幕时，后面翻译的字幕会叠加前面翻译的字幕

### ISSUE THREAD

**Issue by imcby** [1c7/Translate-Subtitle-File#10]
## 问题：
在同一文件夹下，连续翻译多个字幕时，后面翻译的字幕会叠加前面翻译的字幕

## 环境：
- macOS Mojave 10.14.4

## 复现步骤：
1. 找一个多字幕的文件夹
2. 拖入翻译 字幕1，翻译后中英字幕正常显示
3. 拖入翻译 字幕2，翻译后会把 字幕1 的内容叠加到 字幕2 的翻译结果中去，播放时就会同时显示3-4行中英字幕
4. 拖入翻译 字幕3，翻译后会把 字幕1 、字幕2 的翻译结果加到 字幕3 的翻译结果中去，播放时就会同时显示5-6行中英字幕

希望大佬帮忙修复～我平时看MOOC就指望你这个字幕翻译工具了～

**Comment by 1c7** [comment]
咦。。

**Comment by 1c7** [comment]
所以说，先翻译文件1，然后文件2，然后文件3。1是没问题的。2叠加了1，3叠加了1和2。

**Comment by 1c7** [comment]
麻烦你随手扔3个字幕文件到百度云上，然后贴个地址过来？
我修的时候拿真实的文件测试会方便一些

**Comment by imcby** [comment]
> 所以说，
> 
> 操作是：先翻译文件1，然后文件2，然后文件3. 
> 结果是：1是没问题的0.2叠加了1,3-叠加了1和2。

刚刚又试了下，只有第一次是这样。
我把翻译后的字幕删除后，重新开始翻译字幕1时，字幕1竟然叠加了2和3的内容= =

**Comment by 1c7** [comment]
拖入1->拖入2->拖入3->删除1->拖入1 这样？

**Comment by imcby** [comment]
> 拖入1->拖入2->拖入3->删除1->拖入1 这样？

嗯，对的

**Comment by imcby** [comment]
> 麻烦你随手扔3个字幕文件到百度云上，然后贴个地址过来？
> 我修的时候拿真实的文件测试会方便一些

https://pan.baidu.com/s/1qEbRibhmErA9EL0TsMYN9A
nkra

测试字幕

**Comment by 1c7** [comment]
方便百度云扔3个文件？方便我测试？贴个链接让我下载

**Comment by 1c7** [comment]
好哒，收到

**Comment by 1c7** [comment]
我想办法抽时间解决吧，我没法给出具体的解决时间，到时候搞定了我就吱一声

**Comment by imcby** [comment]
> 我想办法抽时间解决吧，我没法给出具体的解决时间，到时候搞定了我就吱一声

好哒，谢谢～

再就是，之前我发现叠加的内容位置是字幕中间，比如字幕3的翻译后的结构是：
字幕3英文——字幕1中文/英文+字幕2中文/英文——字幕3中文

序号什么的都没错，就是多了中间那个part

**Comment by Vost02** [comment]
遇到同样的问题，处理第二个字幕的时候会把一个字幕的翻译叠加进去，必须关掉软件再开才正常。另外也没有办法把中文字幕加在英文字幕上面，而不是分成两部分，这样方便对照修改

**Comment by 1c7** [comment]
@Vost02 问题1没解决嗯。
问题2 "也没有办法把中文字幕加在英文字幕上面" 这个一般改改 Aegisub 里的配置可以做，怎样对换时间轴一样的2行字幕的上下顺序我不太记得了

**Comment by 1c7** [comment]
0.0.2 版已完成，正在进入最后测试，UI 调整和打包。
预计2-4天内可以完成。此问题解决了。先 close isssue

**Comment by 1c7** [comment]
帅哥们，1.0.2版发布了，解决了此问题。可以下载新版使用哟
