### ISSUE TITLE
vtt文件无法翻译吗？

### ISSUE THREAD

**Issue by xu1260114313** [1c7/Translate-Subtitle-File#11]
加个wx：[隐私屏蔽] 我现在只是本地使用vtt功能，代码有点混乱，所以没有告知你。

**Comment by 1c7** [comment]
对。写的很清楚了，目前只支持 srt 和 ass。
vtt 支持暂无计划（因为这个是免费软件，我没空倒腾

**Comment by xu1260114313** [comment]
感谢作者提供源码，我看看是否可以试着改成支持vtt格式。

**Comment by 1c7** [comment]
不过注意，master 分支里有些乱，可以回退几个版本。

我之前 merge 了别人的 PR。那个 PR 里的新改动我怎么都没跑起来。
我自己本地都跑不起来
（我记得是用了个外部的 npm 包，用来弄翻译的）

**Comment by xu1260114313** [comment]
是的，这个源码我也没有直接跑起来。貌似是subtitle-parser这个包有点问题，我尝试修改一下源码。

**Comment by 1c7** [comment]
嗯，你自己随意修改代码，要是改好了可以发个 PR 给我我 merge。
我也不想收拾之前 PR 的烂摊子

**Comment by xu1260114313** [comment]
好的，我尽量。

**Comment by 1c7** [comment]
@xu1260114313  能打扰问一下进度咋样吗？
我打算开发 0.0.2 支持批量翻译功能。（拖入多个文件）
同时提高稳定性（不能一会儿能用一会儿不能用）

如果你有代码没提交的，可以提交一下。
然后我基于你的基础去改

**Comment by 1c7** [comment]
@xu1260114313  Hi, 有收到我上一次留言的 github 通知吗？

**Comment by xu1260114313** [comment]
加个WX：17704208307？我现在只是本地使用VTT功能，代码有点混乱，所以没有告知你.

**Comment by 1c7** [comment]
好的

**Comment by 1c7** [comment]
2019-12-3 vtt 支持加上了。0.0.2 版本收个尾就可以打包了。

**Comment by 1c7** [comment]
在新版 1.0.2 里解决了 vtt 格式问题，麻烦下载新版

**Comment by 1c7** [comment]
https://translation-helper.1c7.me/
