### ISSUE TITLE
新版 無法開啟應用程式「字幕组机翻小助手」。

### ISSUE THREAD

**Issue by WingCH** [1c7/Translate-Subtitle-File#12]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/19588517/70531170-55ae9700-1b8f-11ea-9697-deddbe5d7fa3.png">

**Comment by WingCH** [comment]
發現不用mac原生的軟件解壓就正常了

**Comment by 1c7** [comment]
ok 那问题解决了，我就关掉这个 github issue 了

**Comment by 1c7** [comment]
使用过程如果有问题欢迎继续留言。

**Comment by 1c7** [comment]
补充说明一下，我没有花钱买什么 Apple Developer Program 所以打包的时候没有签名。所以如果 macOS 有一些安全提示是正常的。我这免费软件实在不愿意掏 $99美金交 tim cook 税。以后看看能不能做个 免费版+基础版+高级版。
