### ISSUE TITLE
Google 翻譯20個文件後出現請求失敗

### ISSUE THREAD

**Issue by WingCH** [1c7/Translate-Subtitle-File#13]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/19588517/70531758-8e02a500-1b90-11ea-8d8c-cbdeaad5731c.png">

**Comment by 1c7** [comment]
翻译成功了20多个，之后的都出错？

**Comment by 1c7** [comment]
我现在没有在客户端加任何错误跟踪的东西（比如 Sentry）。我很难定位你那里具体是什么问题

**Comment by WingCH** [comment]
剛好20個 第21個出错

**Comment by 1c7** [comment]
方便的话可以加我 QQ 1003211008 这样沟通会快速一些。不知道你用不用 QQ

**Comment by 1c7** [comment]
试试最古老的方法：关掉程序再打开，然后试试能不能用。

**Comment by WingCH** [comment]
我現在試又可以了，估計有時間上的最高請求限制

**Comment by 1c7** [comment]
程序刚发布，尽管我在自己电脑上测试过了，但是难免在别人电脑上出现问题，多多担待。

**Comment by 1c7** [comment]
好，能用就行。以后我看看要不要在程序里限制下速度，而不是人工来限定速度。

**Comment by 1c7** [comment]
注意一点，谷歌翻译是收钱的，不是免费的。软件本身是免费的，谷歌翻译不是免费的。

**Comment by 1c7** [comment]
悠着点用，不要月末收到一个谷歌发来的大账单

**Comment by 1c7** [comment]
现在刚发布，一些文字说明有些欠缺，我在补文档了，包括具体这几家翻译服务商的收费情况。怎么获取彩云 token，Yandex api key, Azure key 这样的教程都会写。

**Comment by WingCH** [comment]
https://cloud.google.com/translate/pricing?authuser=2&hl=zh-tw

每人每日好像有10美元的免費用量

**Comment by WingCH** [comment]
軟件不錯，繼續加油!

**Comment by 1c7** [comment]
感谢支持，有建议和意见欢迎继续留言。

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/70532429-fd2cc900-1b91-11ea-820d-21ec47387737.png)
我才刚看到$10刀这个事情。感谢告知。不过这里写的是 `每月最多價值 $10 美元的免費用量`。不是每天

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/70532478-16357a00-1b92-11ea-92b1-31ccdd7fbd2e.png)
我之前都是直接看下面的20美刀100万字

**Comment by 1c7** [comment]
既然没问题我就依照 github 的传统，没问题的 issue 我就关了，你有需求的话再随便开新 issue 就是了

**Comment by 1c7** [comment]
这下面也可以继续留言，当聊天板用。只要能沟通就行，方式无所谓

**Comment by WingCH** [comment]
我看錯了 對是每月10美元！

**Comment by 1c7** [comment]
你都是翻译教程看？

**Comment by WingCH** [comment]
對 翻譯教程的英文字幕
之前找的軟件都是英文翻譯中文
但你的軟件會保留英文，看教程的時候中英對照 十分合乎我的需求

**Comment by WingCH** [comment]
另外提個小建議
自定義過濾特定詞語不翻譯
例如Swift, Dart, flutter 等詞語不用翻譯
但實現起來應該有點複雜

**Comment by 1c7** [comment]
@WingCH 对，实现起来的确复杂，所以这个功能暂时不做，假设以后谷歌说『这里有个术语库可以保存不需要翻译的词』。实现起来方便了，就可以做。

**Comment by WingCH** [comment]
找到方法

https://cloud.google.com/translate/faq?hl=zh-tw

先將字幕檔包裝成html格式
需要過濾的詞語

```html
<span translate="no"> </span>
```

api 翻譯後再重新包裝成字幕格式

**Comment by 1c7** [comment]
@WingCH 

看到了
![image](https://user-images.githubusercontent.com/1804755/70585156-3c90ff00-1bfe-11ea-917c-833de1eb1977.png)

之后加进去

**Comment by 1c7** [comment]
技术实现（大致思路）：
把无需翻译的单词全都放到一个数组里。
把待翻译的句子通过空格分割，然后逐个检查单词是否无需翻译。
如果无需翻译就改成 `<span translate="no">单词</span>`

以下伪代码示例
```Javascript
let no_translate = ['Swift', 'Dart', 'flutter'] 

var word_list = "Today we gonna learn Swift".split("")
=> ["Today", "we", "gonna", "learn", Swift"]

 for (word,index in word_list){
   if word in no_translate_array:
      替换为 <span translate="no"> </span>
}
```

**Comment by WingCH** [comment]
再進一步的話可以預設某些詞語不用翻譯，例如全部Language的名稱等，更人性化!

**Comment by 1c7** [comment]
@WingCH 老哥方便加个 QQ 或者微信吗？我 qq 1003211008 微信 agoodob。
想问你谷歌登录后，进行翻译之后，收到了多大的账单金额。

**Comment by 1c7** [comment]
我这边收到了 $95 美金的账单
