### ISSUE TITLE
code view中没有代码了吗？

### ISSUE THREAD

**Issue by xu1260114313** [1c7/Translate-Subtitle-File#14]
代码不支持MIT协议了吗？

**Comment by 1c7** [comment]
代码全部去掉了，之前是开源，现在不开源了，以后我打算弄英文版看看能不能在国外赚点美元。
不开源原因：
1. 想赚钱
2. 大部分目标用户是做字幕的普通人，不是程序员，开不开源完全不影响它们

**Comment by xu1260114313** [comment]
了解了。哈！

**Comment by 1c7** [comment]
好，既然问题解决了那我关掉 issue 了，有问题可以随时开新 issue 或者在这里继续留言。
