### ISSUE TITLE
有2个小问题希望能改进

### ISSUE THREAD

**Issue by kingzleshe** [1c7/Translate-Subtitle-File#15]
1.每次打开软件都要重新选择翻译服务器商，软件无法记忆上次使用过的服务商

2.翻译后的文件默认不是和原来的文件在一个目录，或者能添加手动指定目录功能

**Comment by 1c7** [comment]
收到。会改进这2个功能。感谢建议。
如果有兴趣可以加入用户 QQ 群 982808006。
问题解决了可以及时通知您

**Comment by 1c7** [comment]
> 1.每次打开软件都要重新选择翻译服务器商，软件无法记忆上次使用过的服务商


已解决，下一个版本 1.0.6 会发

> 2.翻译后的文件默认不是和原来的文件在一个目录，或者能添加手动指定目录功能

这个比预期要困难一点，多花一些时间，预计 1.0.7 发
