### ISSUE TITLE
腾讯的报错了

### ISSUE THREAD

**Issue by chenAdmin** [1c7/Translate-Subtitle-File#16]
> 收到，能提供一些信息吗？
> 
> * Window/Mac？
> * 版本 1.0.5还是？
> * 正确配置了腾讯云信息吗？
> * 截个图？

哇 你回复的真快  是说appid不存在 我先试了百度的是可以的

**Comment by 1c7** [comment]
收到，能提供一些信息吗？

* Window/Mac？
* 版本 1.0.5还是？
* 正确配置了腾讯云信息吗？
* 截个图？

**Comment by 1c7** [comment]
正确配置的长度大概是这样的：
![image](https://user-images.githubusercontent.com/1804755/70876358-4d71b400-1ff4-11ea-994e-b7d587c20494.png)

**Comment by 1c7** [comment]
具体配置方法（SecretId 和 SecretKey 从哪里拿）
https://doc.translation-helper.1c7.me/folder/setting/#%E8%85%BE%E8%AE%AF%E4%BA%91
![image](https://user-images.githubusercontent.com/1804755/70876386-65493800-1ff4-11ea-8fcd-625c663082bb.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/70876402-73975400-1ff4-11ea-8d6a-d384602bcbac.png)

![image](https://user-images.githubusercontent.com/1804755/70876409-785c0800-1ff4-11ea-9888-777e5154d467.png)

![image](https://user-images.githubusercontent.com/1804755/70876416-7e51e900-1ff4-11ea-811a-341d2551de87.png)

**Comment by 1c7** [comment]
如果你能给报错信息截图，会对我很有帮助。方便截个图吗？

**Comment by chenAdmin** [comment]
我搞错了 我用的是腾讯ai的翻译 不是腾讯云的。。。。

**Comment by 1c7** [comment]
"腾讯 AI 开放平台" 和 "腾讯云" 是两回事。怪我没有写清楚。不好意思

**Comment by 1c7** [comment]
建议用 "腾讯云"，每月500万免费额度，非常牛逼。
软件不支持 "腾讯 AI 开放平台"

**Comment by 1c7** [comment]
https://cloud.tencent.com/product/tmt/pricing

> 开通免费试用：您可以在每月免费额度内使用，超过免费额度之后请求将会被限制，直到下月初免费额度重新刷新。免费开通将不会产生任何收费账单。  

![image](https://user-images.githubusercontent.com/1804755/70876658-5dd65e80-1ff5-11ea-9cf5-218952dcf398.png)

![image](https://user-images.githubusercontent.com/1804755/70876674-721a5b80-1ff5-11ea-878f-ceea2cefe607.png)

> 文本翻译的每月免费额度为5百万字符。

![image](https://user-images.githubusercontent.com/1804755/70876662-662e9980-1ff5-11ea-903b-0cb8d315594a.png)



![image](https://user-images.githubusercontent.com/1804755/70876643-50b96f80-1ff5-11ea-853d-e90245bff1d5.png)

**Comment by chenAdmin** [comment]
> 建议用 "腾讯云"，每月500万免费额度，非常牛逼。
> 软件不支持 "腾讯 AI 开放平台"

刚才去申请了一个 ，设置好之后开始翻译，前30多行多次报错但是报错之后还可以继续翻译，但是一共220行翻译完218行的时候卡住了 
![image](https://user-images.githubusercontent.com/8599465/70877213-924b1a00-1ff7-11ea-8be2-12ed271720c8.png)

**Comment by chenAdmin** [comment]
> 如果你能给报错信息截图，会对我很有帮助。方便截个图吗？

还有一个问题是一开始用百度的可以翻译，但是翻译完成之后是没有文件的，源目录和“打开文件夹”都没有

**Comment by 1c7** [comment]
了解～ 我看看修复一下 下一个版本 1.0.6 解决这些问题。谢反馈

**Comment by 1c7** [comment]
方便的话可以加我 qq 1003211008 吗？如果我无法重现问题可能还要麻烦你帮个忙。 或者微信 agoodob

**Comment by chenAdmin** [comment]
> 方便的话可以加我 qq 1003211008 吗？如果我无法重现问题可能还要麻烦你帮个忙。 或者微信 agoodob

已经加了

**Comment by 1c7** [comment]
## 结论（给其他人看）：
用"腾讯云"，不是"腾讯开放平台"
