### ISSUE TITLE
腾讯api超出5个并发的限制

### ISSUE THREAD

**Issue by cheng-yuming** [1c7/Translate-Subtitle-File#18]
单任务偶尔会报错，多任务就一定会报错了，希望加个参数控制并发数。
工具很好，十分感谢。

**Comment by 1c7** [comment]
好。 不客气。 方便问一下你的版本号吗？这个问题在最新的  1.1.1 里应该不会出现了

**Comment by 1c7** [comment]
麻烦有空看到回复一下哈

**Comment by cheng-yuming** [comment]
刚看了一下是1.0.5，试一下1.1.1，没问题了。
