### ISSUE TITLE
amazon语音服务有点问题

### ISSUE THREAD

**Issue by baogechen** [1c7/Translate-Subtitle-File#19]
bucket 名称应该设置为可配置，不能写死
否则API报错：
Error: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

**Comment by 1c7** [comment]
好 收到，会改

**Comment by 1c7** [comment]
之前不知道为什么没收到 Github 通知，我是前一条留言时才看到这个 issue。
回到正题，
现在最新版  2.4.0（我刚加了讯飞进去）
下个版本 2.4.1 修复下 amazon 这个问题。
今天5月26号，预计5月29号之前发布

**Comment by 1c7** [comment]
版本 2.4.1 已发布，此问题解决，close issue
可继续留言讨论
