### ISSUE TITLE
翻译后中文字幕滞后了一句话

### ISSUE THREAD

**Issue by 5cr1pt** [1c7/translate-subtitle-file#2]
[(翻译后)L1_S7-en.txt](https://github.com/1c7/translate-subtitle-file/files/2346345/L1_S7-en.txt)
字幕文件，后缀请改为.srt查看

**Comment by 1c7** [comment]
get

**Comment by 1c7** [comment]
我其实之前好像也有碰到这个问题。但是最近工作忙，我实在没法马上修这个事情。
可能等周末吧？

**Comment by 1c7** [comment]
感谢使用 & 感谢反馈

**Comment by 1c7** [comment]
@eyasliu 的 PR 里应该修复了这个问题，那么这个 issue 我就先关掉了。
