### ISSUE TITLE
用腾讯云的文字翻译接口问题

### ISSUE THREAD

**Issue by palorotolo** [1c7/Translate-Subtitle-File#21]
-这是个负担，相信我.
‐ It's a burden, believe me.

例如这种，「- 」会被翻译成「-」，去掉了一个空格

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/82918892-e9421b80-9fa7-11ea-8170-aeaf19d85d72.png)

腾讯云本身就是这样处理的

你可以全局替换 "-" -> "- "

**Comment by 1c7** [comment]
这锅交给腾讯云哈哈

**Comment by palorotolo** [comment]
全局替换不行，因为还有很多其他地方用了「-」

**Comment by 1c7** [comment]
那这样判断你看行不行
仅在某行第一个字符是 "-" 时，把它换成 "- "

**Comment by 1c7** [comment]
不过这样还是有缺点，因为
```
- x
- y
```
有时候一句里面会是这样的"两句"，腾讯云是完全忽略 \n 的。这一句的返回结果，实际上会被拼到一起
变成
```
- x -y
```

**Comment by 1c7** [comment]
如果使用量不大（两百万以下）
随便换其他服务商都可以，小牛，百度，彩云，阿里云，都可以试试
不嫌申请麻烦的话甚至有道，搜狗都可以试试

**Comment by 1c7** [comment]
最近 DeepL 在 mac 版上线了，可以试试

**Comment by 1c7** [comment]
此 issue 太久没有进展，因此关闭，但如有必要，仍可继续留言讨论
