### ISSUE TITLE
Please add DeepL

### ISSUE THREAD

**Issue by hysencn** [1c7/Translate-Subtitle-File#22]
![image](https://user-images.githubusercontent.com/60783595/87947326-bf9fff00-cad5-11ea-92f1-d3bce04c1ac6.png)

10 translators, not 13 translators. 
Thanks.

**Comment by 1c7** [comment]
@hysencn this software provider 2 languages version. Chinese and English.
DeepL does exists. but only in Chinese version.
because the instruction about how to set up is in Chinese

**Comment by 1c7** [comment]
用软件的中文版
![image](https://user-images.githubusercontent.com/1804755/87950227-9aad8b00-cad9-11ea-9044-7e3dc552a661.png)

**Comment by hysencn** [comment]
感谢大佬, 这个 app 做得真美. 
DeepL 在 6 月 16 日开放日本区购买, 中国区应该不会太久. 
DeepL 官方订阅的优惠价格是需要整年一次性支付的, 所以应该可以找代购购买, 
我暂时也没找到合适的代购商. 大致就是这个方向了.

**Comment by 1c7** [comment]
好勒

**Comment by 1c7** [comment]
如果没后续问题的话我就先关闭 issue 了。
有什么想补充的可以再追加，或者开个新 issue，都可以。
