### ISSUE TITLE
[字幕文件翻譯] 翻譯後檔案名的標點符號會消失

### ISSUE THREAD

**Issue by WingCH** [1c7/Translate-Subtitle-File#23]
翻譯後檔案名的標點符號會消失

> 翻譯服務商: Google, 源語言: 英語, 目標語言: 中文(繁體)

`2-What is Serverless?.srt` 變成 `2-What is Serverless.srt`

![image](https://user-images.githubusercontent.com/19588517/89125159-f4b54400-d50e-11ea-9305-128ee18ef2f7.png)

設定: 

![image](https://user-images.githubusercontent.com/19588517/89125227-7dcc7b00-d50f-11ea-97a9-14ee2b4ea4ec.png)

軟件非常好，再剛開始用到現在，作者加油！

**Comment by 1c7** [comment]
还蛮奇怪的，为啥标点会消失。
我好像做了个 sanitize filename 的动作。可能是这个原因，不太记得。
我去查阅一下代码。

**Comment by 1c7** [comment]
好，感谢支持！

**Comment by 1c7** [comment]
这个问题修好之后发布到下个版本里。现在的最新版是 2.9.0。下一个版本是 3.0.0

**Comment by WingCH** [comment]
好的, thanks! 好有效率
