### ISSUE TITLE
srt英译中 彩云翻译后符号消失

### ISSUE THREAD

**Issue by jzysl123** [1c7/Translate-Subtitle-File#24]
例如翻译
`<i>my buddy.</i>`
我的朋友

`<i></i>`符号消失 是不是彩云的锅。。。

**Comment by 1c7** [comment]
翻译的时候会去掉 html 标签。

**Comment by 1c7** [comment]
如果把 html 标签也带过去翻译，会扰乱结果。
彩云官网提供了一个网页版的翻译（类似谷歌那种左右各一个框的界面）
你可以试试复制这样的文字进去，得到什么结果。

**Comment by 1c7** [comment]
翻译前会统一去掉 html 标签，但是保留标签里面的文字。
这是 2.7.0 加进去的新功能，之前的版本有用户反馈 html 标签会干扰结果，所以加了这个功能。

**Comment by 1c7** [comment]
简而言之：这是正常的行为。

**Comment by 1c7** [comment]
目前软件里没有开关可以控制 "翻译前去除 HTML 标签"。因为我是写死的。
