### ISSUE TITLE
语音识别时间过长

### ISSUE THREAD

**Issue by DefetC** [1c7/Translate-Subtitle-File#25]
两小时长的英文语音识别了一个小时还未成完成，请问这是正常的么？用的阿里云。
![image](https://user-images.githubusercontent.com/20338520/91050120-8bce7100-e661-11ea-87be-bf2b76d92c4d.png)

**Comment by DefetC** [comment]
阿里云使用的商用服务，没有时间限制。

**Comment by 1c7** [comment]
你好，有的情况下这个状态的显示不太对（这也不好复现问题，能复现就肯定修了）
可以通过 设置-> 阿里云 -> 任务历史。
在任务历史界面，查证这个任务的确切情况。

**Comment by 1c7** [comment]
从个人经验来说，阿里云的语音转文字服务是非常快的。
IBM  这样的服务商才慢，IBM  需要的时间是音频的 0.5x 到 1x 的时间（比如20分钟的音频最少要花10分钟，甚至可能花20分钟）

**Comment by DefetC** [comment]
> 你好，有的情况下这个状态的显示不太对（这也不好复现问题，能复现就肯定修了）
> 可以通过 设置-> 阿里云 -> 任务历史。
> 在任务历史界面，查证这个任务的确切情况。

任务历史里也只有“正在获取结果...”。目前我有些怀疑是不是因为我人在澳洲，网络环境太烂，上载或者下载中出现了问题。。。。

**Comment by 1c7** [comment]
982808006 是用户 q.群号。
1003211008 是我 qq。
如果文件不敏感可以用 qq 发我。然后我来试试。看看能否复现问题

**Comment by 1c7** [comment]
此问题已通过私聊解决。close
