### ISSUE TITLE
readme文档说明很多错误，有误导用户的嫌疑

### ISSUE THREAD

**Issue by patui** [1c7/Translate-Subtitle-File#28]
`不推荐腾讯云，字幕断句有问题（一句一大段文字）如果只是想输出纯文字，那问题不大，但如果需要字幕，那质量很差，一句话很多个字，在屏幕上会显示4-5行，占满半个屏幕，影响观看，如果自己去调整时间轴又比较费时。`

我自己的测试，腾讯云的语音识别效果远好于阿里云的语音识别，你没看错，远好于阿里云，腾讯云语音之所以有一句一大段的问题，是因为文件转写本身并不是完全针对字幕场景的，需要开发者根据接口返回的分词数据，自行断句切割，而腾讯云语音识别的API接口已经提供了分词功能，这个工作要开发者来完成。

另外腾讯云的翻译也是如此，
如果我没有看错接口，腾讯云翻译也是支持一次翻译多句话的，请认真阅读文档。

**Comment by 1c7** [comment]
好的

**Comment by 1c7** [comment]
我会再次检查，并根据实际情况进行修正

**Comment by 1c7** [comment]
感谢提醒，也许是我做的时候有疏漏没看到

**Comment by 1c7** [comment]
由于这几天在北京出差（我住在广州）可能要12月初才能解决这个问题

**Comment by 1c7** [comment]
刚还去逛了腾讯北京总部（朋友带的）

**Comment by 1c7** [comment]
先 closed

**Comment by dingzeyuli** [comment]
初步使用，觉得这个app是同款里面最简单直观的，特别是为码农设计的！谢谢你的产品！

有两个建议：
1. 像上面这位提的建议，修正腾讯云的字幕断句的bug
2. 提供一档傻瓜式的服务，就是用户不用去配置任何的东西，只用往你的app里充钱就好了，你自己在后段用你的配置好的bucket和service来服务。这样子可以方便更多不想去配置各种云服务的人。

**Comment by 1c7** [comment]
@dingzeyuli  明白~感谢夸奖。
关于第二点（傻瓜式的服务）推荐你关注一下 字幕酱 https://www.zimujiang.com/
这个就是直接充钱就能用，这是我朋友做的（因为大家都做同一个领域的产品，聊聊就认识了）
我不乐意做一款傻瓜式服务的工具，是因为字幕酱已经满足了这个需求
我没必要重复做一个，字幕酱目前已经有规模优势了，所以价格很低，我打价格战也是打不过的。

对我来说做一款能替代 Aegisub / Arctime 的字幕编辑软件，才是当前的重点，也是我喜欢做的。
https://github.com/1c7/Subtitle-Timeline-Editor

最后，感谢建议，
如果用机翻助手的过程中有其他建议和想法欢迎随时沟通

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/108629525-43baca80-749b-11eb-9a9d-b2e709c96418.png)
## 更新
这一篇是完全正确的。

我今天仔细看了一下（过完年终于有空来继续开发了）
1. 腾讯翻译现在支持一次性传入多行了（用 \n 换行即可）
2. 腾讯语音转文字也支持返回词的时间戳。而不是之前那样一大句。

想了一下，我开发的时候是2020年上半年的时候，大概2月份还是多少。当时的确是不支持多行也不支持返回词的。
后来支持的。
很棒，给腾讯云点个赞。

**Comment by 1c7** [comment]
相关文字说明已更新 https://github.com/1c7/Translate-Subtitle-File/commit/08b5cddde027899a4b4fe18ea99ba8d2649e3830

**Comment by 1c7** [comment]
提供多一点信息：之前开发时，用的是 v3 SDK
目前最新版是 https://www.npmjs.com/package/tencentcloud-sdk-nodejs
4.0.65
