### ISSUE TITLE
用了ffmpeg进行转码吗？

### ISSUE THREAD

**Issue by dingzeyuli** [1c7/Translate-Subtitle-File#29]
我不知道你的音频转码用的是不是ffmpeg，如果不是的话，请忽略这个issue。

如果是的话，ffmpeg是LGPL的license，如果是ship一个commercial product（我觉得你的app是），是有对应的要求的。相关链接：
1. https://video.stackexchange.com/questions/14802/can-i-use-ffmpeg-in-a-commercial-product
2. http://ffmpeg.org/legal.html

**Comment by 1c7** [comment]
好的，学习了，我仔细看看

**Comment by 1c7** [comment]
先关了，感谢楼主提供的意见
