### ISSUE TITLE
希望能增加批量翻译字幕文件功能

### ISSUE THREAD

**Issue by leeming0513** [1c7/translate-subtitle-file#3]
首先谢谢作者的无私贡献，把此翻译小助手开源，小助手美中不足的是没有批量翻译字幕文件的功能，对于需批量翻译的字幕文件（如：国外的电视剧等），需单个拖拽翻译工作量比较大，所以希望作者在百忙之中能够抽出时间给翻译小助手增加批量翻译字幕文件功能。

**Comment by 1c7** [comment]
功能可以做。时间上不确定。最近工作忙我没办法给出一个时间比如“这周末完成” 之类的。
这事儿我记着。有空就做。

操作方式：
1. 多选 .srt/.ass 文件然后拖进去。
2. 直接拖一个文件夹进去（只处理文件夹里的 .srt/.ass 文件）

我到时候看看哪个方便写（代码）。或者两个都写。

**Comment by leeming0513** [comment]
@1c7 好的,谢谢。还有想询问一下，配置科学上网，只能全局，不能使用系统代理？

**Comment by leeming0513** [comment]
@1c7    proxifier可以指定某个程序走代理，其余网络直连。 也可以配置为全局代理。 但是我使用proxifier配置全局代理后，小助手翻译不了，  你可以测试一下看行不行。

 proxifie download url： https://crackingpatching.com/2018/09/proxifier-v3-42-keygen.html

**Comment by 1c7** [comment]
@leeming0513
嗯，我有空试试，现在是周三下午1点，我继续工作了~

**Comment by leeming0513** [comment]
@1c7   好了，我也要继续搬砖了。

**Comment by versioneg** [comment]
@1c7 作者你好，我配置了VPN，为什么点了翻译还是没有反应了，用浏览器上youtube都没有问题， 我使用的是win8系统，不知是什么原因呢？

**Comment by 1c7** [comment]
@versioneg 
可能原因1：VPN 没有弄成全局代理。导致点击"翻译"后，小助手的网络请求依然走的国内路线，谷歌翻译自然就访问不到了。
可能原因2：谷歌修改了他们的 API 接口。导致小助手的程序出错。

解决方法：翻墙弄成系统全局的。如果还是不行。那我得检查下程序了。我得自己本地跑一下看看有没有问题。

我自己很久没有翻译字幕了。我自己有好几个月没有打开过小助手了
