### ISSUE TITLE
Azure gets stuck in "上传进度 0.28%"

### ISSUE THREAD

**Issue by CicoZhang** [1c7/Translate-Subtitle-File#31]
The region is set to Western Europe. It seems that no uploading really takes place; perhaps the connection is not successful.

![image](https://user-images.githubusercontent.com/11710225/111540386-62953f80-876f-11eb-904f-e7f5f667a295.png)
![image](https://user-images.githubusercontent.com/11710225/111540429-6e810180-876f-11eb-87b0-62ff41a0c2cd.png)

Thanks. :-)

**Comment by 1c7** [comment]
如果人在国内 翻墙
如果不在国内 试一下 eastus

**Comment by CicoZhang** [comment]
多谢回答。 人在欧洲，切换成 eastus 的 storage account, 测试依然不通过。
![image](https://user-images.githubusercontent.com/11710225/111638802-f8c27780-87fa-11eb-81dc-42d9716d4f4a.png)

**Comment by 1c7** [comment]
emmmm 真是神了

**Comment by 1c7** [comment]
您是最新版的 4.1.0 吗？（目前 2021-3-18 的最新版是 4.1.0）
如果不是，先更新到最新版，试一试。
如果不介意的话可以加我 QQ 1003211008，我用你的配置试一试，然后根据报错信息调试一下，如果有问题就修复

**Comment by CicoZhang** [comment]
多谢，已经通过 Telegram 联系你了。 软件是 最新版 4.1

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/111646853-f8e36700-883c-11eb-8827-c0d4f88d561e.png)
留个底，供其他用户参考
```
{ "code": "InvalidSubscription", "message": "Only \"Standard\" subscriptions for the region of the called service are valid." }
```

使用这位用户提供的配置信息后，报错信息如上，意思就是只有 `Standard` 订阅是 valid 的。

**Comment by CicoZhang** [comment]
测试两台电脑，也通过VPN，发现4.1都无法跟Azure 正常通信，然后试了试 3.9 版本，发现问题消失了。

**Comment by 1c7** [comment]
（留底供查阅）
@CicoZhang 反馈说换成 3.9 之后问题消失了，现在在继续使用 3.9。
按理来说应该是越更新越好的，现在 4.1 反而比起 3.9 还有一些不足，不应该。
印象里我记得是给  Azure 升级了，可能是因为升级导致了一些问题，到时候会查查看

**Comment by 1c7** [comment]
先 close 掉这个 issue，如有需要可以继续讨论

**Comment by fireattack** [comment]
同样遇到此问题 3.9工作正常
