### ISSUE TITLE
请问可以支持 Linux 吗？

### ISSUE THREAD

**Issue by woshichengpeng** [1c7/Translate-Subtitle-File#32]

**Comment by 1c7** [comment]
可以 按理来说打包一个 linux版是没问题的
因为是electron.js
不过我没试过。
最近比较忙，可能没空做这个。
有空的时候可能mac上跑个ubuntu虚拟机打包试试

**Comment by 1c7** [comment]
现在支持了，可以直接用网页版 https://tern.1c7.me/#/
