### ISSUE TITLE
语音转文字（谷歌）正确配置账户信息后无法测试成功

### ISSUE THREAD

**Issue by Huaweidev** [1c7/Translate-Subtitle-File#34]
语音转文字（谷歌）正确配置账户信息后无法测试成功
已为谷歌云账户配置了均在相同地域的语音转文字服务帐号 (Service accounts) .json和对象存储桶名称。但是多次测试等待较长时间也无法显示测试成功。
客户端版本：windows 4.1.0
![05-25_23-23](https://user-images.githubusercontent.com/10258421/119527566-0411c080-bdb3-11eb-98cb-888b1192d2b8.png)

**Comment by 1c7** [comment]
你好，请开启全局翻墙

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/119531486-8cde2b80-bdb6-11eb-9736-18d1a954c816.png)

**Comment by 1c7** [comment]
如果你的 VPN  开启了全局翻墙，就会像我上方提供的截图一样，全部测试成功。
如果你的 VPN 是那种监听本地端口比如 2801，2802，那么你需要在 HTTP_PROXY  的部分填一下。
并且HTTP_PROXY 输入框右上角的开关改成开启。

**Comment by Huaweidev** [comment]
> 如果你的 VPN 开启了全局翻墙，就会像我上方提供的截图一样，全部测试成功。
> 如果你的 VPN 是那种监听本地端口比如 2801，2802，那么你需要在 HTTP_PROXY 的部分填一下。
> 并且HTTP_PROXY 输入框右上角的开关改成开启。
SOCKS5代理服务器http://127.0.0.1:1080填写无法测试成功，如何添加本地SOCKS5代理服务器？

**Comment by 1c7** [comment]
这个应用是用 Electron.js 写的。
https://www.electronjs.org/docs/api/session#sessetproxyconfig

![image](https://user-images.githubusercontent.com/1804755/119538001-39231080-bdbd-11eb-937a-65d00773f18d.png)

![image](https://user-images.githubusercontent.com/1804755/119538031-42ac7880-bdbd-11eb-9b68-0d002752f89a.png)

![image](https://user-images.githubusercontent.com/1804755/119538096-56f07580-bdbd-11eb-84bb-b9d6349c428a.png)

## 长话短说
以下这种也许可以，你得试一试
```
socks5://127.0.0.1:1080
```

**Comment by 1c7** [comment]
需要特别说明的是，软件的收费和服务商的收费是两回事。
软件的收费（比如7天3.5元）是为了完全解除天花板限制（当前天花板是一个月100万翻译字符，10个小时语音转文字）
服务商的收费是单独的，比如阿里云每天2小时免费额度，超过了就会阻止你继续使用（如果开了商业版就另说）商业版好像是3.5元一个小时。

谷歌的收费大概是8-9块钱一个小时？我不记得了，我上次看好像是 1.44 美金一个小时还是多少。
你自己看一下。
不要月底收到谷歌的一个大账单然后跑来问我咋回事。

这个在使用前应该明确知道

**Comment by Huaweidev** [comment]
> 这个在使用前应该明确知道。

明确知道了，请放心。
