### ISSUE TITLE
问卷调查：是否需要命令行版本的机翻助手？（请用户们留下你宝贵的意见）

### ISSUE THREAD

**Issue by 1c7** [1c7/Translate-Subtitle-File#35]
## 解释
当前这个机翻助手的桌面端软件，需要拖入/选择后进行操作（操作前需要设置服务商配置）

## 目标
有些程序员用户希望在命令行处理

## 问题
1. 你是否需要这样一个命令行工具？
1. 目前有2个功能"字幕文件翻译" 和"语音转文字"，如果做成命令行，你希望先实现哪个？对你而言哪个用的比较频繁，价值大一些？
2. 收费方面，有什么看法可以分享？
  * 备注：收费肯定要收的，只是多少和方式的问题

**Comment by 1c7** [comment]
```bash
tern-subtitle-translator --srt-file "~/Download/1.srt" --source-lang="en" --target-lang="zh-cn" --output-file "~/Download/1-zh-cn.srt"
```

**Comment by 1c7** [comment]
我倾向于用  node.js 写个命令行，但是不知道怎么弄成二进制。
暂时不熟悉 go 或者  rust（他们估计可以编译成二进制）

**Comment by WingCH** [comment]
1. 我的使用場景是看下載英語的課程後利用助手獲得中文字幕，所以可能對命令行工具需求不大。
2. 沒事意見
3. 收費方面，我認為現在這個軟件一般的使用場景是單獨一次一次的。例如我的情況來說，我找到一套課程然後就會使用工具幫我翻譯，但是我不會每天也找到不同的課程來學習，所以可能實際使用次數一個月才一次。收費方面可以考慮一下以次數收費 好像iText 每月有一定的免費次數限額，如果超過改免費限額就要收費

**Comment by WingCH** [comment]
另外或許可以改變一下現在軟件的模式
現在需要我們自己到不同的服務商申請API Key 然後填入軟件內才可以使用翻譯功能

這個門檻我感覺對於不是讀IT的使用者會卻步，他們正常都會懂得如何設定

所以如果有一個獨立的版本或一個模式 是不需要他們自行設定 你幫他們設定好，然後再按時收費（因為服務本身要錢的），這樣可以平衡你的成本，長遠來說可以吸納更加多的用戶

**Comment by 1c7** [comment]
@WingCH 收到！感谢建议

**Comment by 1c7** [comment]
我等工作日来具体回复一下

**Comment by photkey** [comment]
强烈支持命令行版，有命令行版的话，可玩性更高。昨天在找语音转字幕工具，就是在这个项目跟autosub之间犹豫，这个项目明显功能更强、支持的接口更多。但是autosub支持命令行操作，可以玩出更多花样来。
比方可以非常轻松的借助AHK脚本实现：选中一个音频/视频， 然后按下一个快捷键 就一键转出字幕文件了，没有比这更快的操作了。

**Comment by 1c7** [comment]
@photkey  好的，收到

**Comment by 1c7** [comment]
命令行版本想做，但是不确定收费怎么实现，不确定用户数量会有多少，投入产出是否合理
