### ISSUE TITLE
感谢作者的开源翻译软件,但是有英语==>中文吗?

### ISSUE THREAD

**Issue by Ericxiaoshuang** [1c7/translate-subtitle-file#4]
貌似只有英文转换==>中文
没有中文====>英文的选项吗
可以设置一个开关按钮
提供这个功能吗

**Comment by 1c7** [comment]
做可以做，只是需要时间，最近又比较忙，所以我没法给个时间排期说大概X月X号做好 = = 
这样吧，哪天我要是有空顺带做了，和你说一声

**Comment by 1c7** [comment]
同样，因为 RP 里修了，这个 issue 关掉
