### ISSUE TITLE
希望增加使用Apple本地语音识别功能转换字幕

### ISSUE THREAD

**Issue by suliveevil** [1c7/Translate-Subtitle-File#43]

**Comment by 1c7** [comment]
我之前从来没想过用这个东西，感谢提醒。
看了一眼似乎是：https://developer.apple.com/documentation/speech

Perform speech recognition on live or prerecorded audio, receive transcriptions, alternative interpretations, and confidence levels of the results.

![image](https://user-images.githubusercontent.com/1804755/146315210-6216ed92-f0cc-48d4-a2a0-3c4b5a5158a8.png)

我可能得用 Swift 写一个 command-line interface (CLI) 弄成二进制得到一个文件。然后通过某种方式用 Electron.js 来和这个文件交互，把文件交给它，让他 speech to text 之后把 text 还给我

**Comment by suliveevil** [comment]
离线主要是为了安全😂，可能准确率不如在线的但没有使用上的限制。
目前我发现的用Apple 自带语音识别的iOS/iPadOS app有：VoiceNotebook、Vrew，macOS上：YPlayer和Be My Ears（这俩是一家，实时字幕，暂时没有导出功能）。
可以导出字幕但需要上传数据的：飞书、雅婷逐字稿、Otter、Notta。
讯飞在App Store里弄了一堆账号发了一堆app都是用自己的云做STT，都没有导出字幕功能。

**Comment by 1c7** [comment]
学习了，原来如此。

也就是说
* VoiceNotebook
* Vrew
* YPlayer
* Be My Ears 
都有识别功能但无法导出

* 飞书
* 雅婷逐字稿
* Otter
* Notta
可以导出

**Comment by 1c7** [comment]
那为啥不用可以导出的那4家产品？（飞书，雅婷逐字稿，Otter，Notta）
不太懂

**Comment by suliveevil** [comment]
飞书免费，但比较复杂；
雅婷逐字稿是台湾人出的对普通话支持不太好；
Otter太贵了；
Notta是日本人出的，价格比Otter便宜。

如果考虑离线使用、安全性的话，市面上没有比较好的解决方案。

单纯语音转文字，不要求字幕的话，iOS/iPadOS上的 Just Press Record做的就挺好，使用Apple语音识别，后台转文字（Voice Notebook需要播放音频），一次性买断。

**Comment by 1c7** [comment]
懂了。感谢。省了我很多市场调研的工作，哈哈。
我最近在把这个 Tern (机翻小助手) 从 Electron.js 10 升级到 15。
把这阵子阵痛期过了之后，后面就可以放开手脚搞新功能了。
我这边也在 QQ 群里整天给用户催别的功能。

后续我把 Apple 本地这个做好之后，会在这个 issue 里和你说一声。
不过可能没那么快，现在都12月了。有可能得到2022年了

**Comment by suliveevil** [comment]
期待😊

**Comment by 1c7** [comment]
@suliveevil 好奇多问一句你的用例和用量大概是什么？
比如你都是用来弄教程的语音转文字？
用量大概是一周转10来个小时的视频？

**Comment by 1c7** [comment]
我最近也在学 SwiftUI，可能到时候再另外做一个 macOS 的原生 App。
我得先调查一下，因为我觉得类似的 App 应该已经存在了（不过可能价格贵）

**Comment by suliveevil** [comment]
我目前是自己在iPad和Mac上剪视频发哔哩哔哩，用剪映生成自动字幕。
在iPad和iPhone上用 Just Press Record 记录个人的语音。

安卓手机里有几百条通话录音没法检索，打算转成文字/字幕。

出于个人兴趣，用量很小，所以也就没有订阅Notta和Noted这种服务，只买了 JPR。

**Comment by 1c7** [comment]
明白了~
