### ISSUE TITLE
希望能给macOS弄个M1版本

### ISSUE THREAD

**Issue by billzt** [1c7/Translate-Subtitle-File#45]
现在这个intel版本太耗电了

**Comment by 1c7** [comment]
理由非常充分，不过 
1. 我没有 M1 电脑，
2. 我不知道咋编译 M1 版本。

这玩意是 Electron.js 写的，我在升级从 Electron 10 升级到  Electron 15，愁死我了，好多代码要改。

**Comment by 1c7** [comment]
总之：
1. 这个需求我记下了
2. 我也不知道要多久完成

**Comment by 1c7** [comment]
现在 Electron.js v32 （软件版本 v5.2.0 在用）打包出来的版本是 arm64，此问题应该是解决了
