### ISSUE TITLE
deepl免费版 失效了 还会修复吗 大佬

### ISSUE THREAD

**Issue by ainy0315** [1c7/Translate-Subtitle-File#46]
n: waiting for selector `.lmt__translations_as_text__text_btn` failed: timeout 30000ms exceeded

**Comment by 1c7** [comment]
不会修复 DeepL 的免费版本了，现在有3-5个用户报告同样的问题了。下个版本会删掉 DeepL 免费版。
下次会加上 DeepL 的付费版本（就是要去 DeepL 注册账号并获取 API key 的那种)

**Comment by 1c7** [comment]
机翻助手的新版本遇到一些开发进度问题，挺慢的。得先修复和处理其他优先级更高的事情。

**Comment by 1c7** [comment]
网页版开发好了 https://tern.1c7.me/#/
您可以试试。目前网页版只支持百度翻译。

DeepL 付费版我会在近期加上。DeepL免费版以后不会再有了。
