### ISSUE TITLE
失败原因: TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by udterry** [1c7/Translate-Subtitle-File#49]
翻译完出现这个报错

**Comment by 1c7** [comment]
字幕文件，服务商，语言配置，告知我一下。我试试。

**Comment by ilovesusu** [comment]
```
...

33
00:01:43,290 --> 00:01:45,116
null
‫why you might want to ‫jump up to the paid...

...
```

双语翻译结果中出现null的情况,通常是出现在整个文件的中间部分.

**Comment by 1c7** [comment]
@ilovesusu 扔个例子 srt 文件给我（原文件和结果文件）
告诉我服务商和语言配置。我重现一下试试

**Comment by ilovesusu** [comment]
@1c7
[百度QPS10.zip](https://github.com/1c7/Translate-Subtitle-File/files/9676301/QPS10.zip)
百度翻译  英文->简体中文  QPS 10 其他都是默认配置

**Comment by udterry** [comment]
> 字幕文件，服务商，语言配置，告知我一下。我试试。

百度，英译中，输出译文，覆盖源文件。
全局替换词表 关闭
合并文字重复的行 开启
字幕翻译成中文后，把逗号和句号换成一个空格 开启

**Comment by 1c7** [comment]
收到，我有空了修一下

**Comment by xeuyuuyuex** [comment]
修复了吗... 出现一样的问题

**Comment by 1c7** [comment]
这个是 bug，我还在开发下一个新版本

**Comment by 1c7** [comment]
https://tern.1c7.me/#/ 
网页版好了，麻烦 @xeuyuuyuex 和 @udterry 和 @ilovesusu 试试
