### ISSUE TITLE
OpenAI 的翻译模型 Whisper 开源了，考虑整合吗？

### ISSUE THREAD

**Issue by mefengl** [1c7/Translate-Subtitle-File#50]
https://github.com/openai/whisper
就是提一嘴，随时 Close 该issue

**Comment by 1c7** [comment]
感谢告知，我才刚知道。
我最近在看 HuggingFace 还没看明白……

**Comment by 1c7** [comment]
暂时先关闭 issue，赶明儿我看看 PyTorch 和一些其他基础的东西。
现在我还是 机器学习的菜鸡

**Comment by 1c7** [comment]
Fast AI 的课好像不错，刚开始看 Lession 1

**Comment by 1c7** [comment]
赞
