### ISSUE TITLE
选择 百度 翻译SRT字幕，运行没有报错，但总是在返回的srt字幕中随机地出现一大段一大段的 null 的字样。

### ISSUE THREAD

**Issue by tomeleon** [1c7/Translate-Subtitle-File#51]

**Comment by tomeleon** [comment]
QPS已经设置为1，如果把SRT字幕手工拆分，再次提交，又会得到少一些null结果的反馈。但是null仍然频繁出现。

**Comment by tomeleon** [comment]
我想应该找到原因了。百度对免费版的单词翻译请求限定在1000个字符。所以可以解释为什么拆分之后能够降低null出现的频率。是否可以考虑在后续版本中集成拆分多次提交的功能。

**Comment by 1c7** [comment]
噢这样啊，我这个最新版 4.1.0 是2021年大概4月发布的，应该是之后百度又做了一些修改，所以有这些问题

**Comment by 1c7** [comment]
新版本会在2022年11月之内发布，因为面包多更换域名的原因，很多用户的激活都收到了影响

**Comment by 1c7** [comment]
https://tern.1c7.me/#/
网页版开发好了，您可以使用了。
目前支持百度。
