### ISSUE TITLE
请问近期是否还会更新？

### ISSUE THREAD

**Issue by Breeze-Zero** [1c7/Translate-Subtitle-File#55]
很感谢您的工作，让我在字幕上的工作轻松很多

**Comment by 1c7** [comment]
近期会更新，这3天内就会发布一个 web 版本，会方便很多，网页直接访问。

**Comment by 1c7** [comment]
如果用QQ，可以考虑加用户 QQ 群 982808006 和 658774053
一群和二群。里面会有通知（如果有重要更新）

**Comment by 1c7** [comment]
网页版做好了 https://tern.1c7.me/#/
目前只有百度这一个翻译服务商，我近期会添加 DeepL 和腾讯。
等腾讯加进去了，再考虑下一步做什么。
