### ISSUE TITLE
语音转文字 Azure设置Connection String报错

### ISSUE THREAD

**Issue by kif5** [1c7/Translate-Subtitle-File#57]
按照教程复制填写Connection String后，点击测试出现以下报错：
错误: 无法解析 Azure 返回的结果，无法判断容器 tern 是否成功创建

**Comment by 1c7** [comment]
因为坏掉了，Azure 这个功能坏掉了。
我现在主要在更新网页版 tern.1c7.me。

桌面版上的功能一个个做到网页版上
