### ISSUE TITLE
准备打包 v0.0.2

### ISSUE THREAD

**Issue by 1c7** [1c7/Translate-Subtitle-File#6]

**Comment by zhoudongshi** [comment]
哇，期待期待，感谢。

**Comment by 1c7** [comment]
最近忙，可能还得耽误一阵子

**Comment by leeming0513** [comment]
@1c7 搬了几个月砖，终于等到作者更新了，期待新版本。

**Comment by leeming0513** [comment]
> 从去年说到今年我还没打包 ~ （man_facepalming

@1c7 万般无奈，我只能选择默默地原谅你。

**Comment by xuyinai** [comment]
期待大佬打包~~~

**Comment by leeming0513** [comment]
@1c7 转眼之间，又过了半年啦……

**Comment by 1c7** [comment]
@leeming0513 
0.0.2 我之前本地跑不通… 不敢碰了…

**Comment by 1c7** [comment]
@leeming0513 好奇问下你想要的新功能是什么

**Comment by hpp0hpp** [comment]
我想要批量翻译，或者能提供命令行，我可以批量处理SRT

**Comment by 1c7** [comment]
@hpp0hpp OK 明白了，你需要 批量翻译功能， 直接拖入10个20个文件，一次性都翻译了，不用一个个拖入

**Comment by zhoudongshi** [comment]
> @hpp0hpp OK 明白了，你需要 批量翻译功能， 直接拖入10个20个文件，一次性都翻译了，不用一个个拖入
多个SRT字幕文件
https://pan.baidu.com/s/1qlERv5Fnd8txsCznFC9i6A

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/64518654-233d9580-d325-11e9-8dbe-cea8e470847d.png)
只要我在坚持摸鱼3个月，这个 issue 就正式获得"1年都没解决"的成就了

**Comment by leeming0513** [comment]
@1c7  期待批量翻译功能。
老哥，我已经等了10个月了，不介意再苦等10个月……

**Comment by 1c7** [comment]
我被炒掉了，现在有空了，我看看这几天如果可能的话，把批量翻译功能做一下，暂不确定

**Comment by 1c7** [comment]
之前老是说工作忙，现在这个问题解决了哈哈

**Comment by 1c7** [comment]
@zhoudongshi 

你给的源文件里格式有点小问题，这个冒号应该是逗号才对。这个应该是网站自己加进去的，但是加进去还加错了。
我只是顺带告知一下而已，你那边不需要采取任何动作。

![image](https://user-images.githubusercontent.com/1804755/65946051-d5213b00-e467-11e9-8e37-c00e74edced4.png)

![image](https://user-images.githubusercontent.com/1804755/65946076-ec602880-e467-11e9-866c-5b141ba6f4a9.png)

**Comment by 1c7** [comment]
哈哈哈又要过一年了

**Comment by 1c7** [comment]
0.0.2 马上上线，接下来2-3天

**Comment by 1c7** [comment]
2018年12月24号开了这个 issue。
现在 2019年12月10号终于可以关掉了

**Comment by 1c7** [comment]
1.0.2 版发布了（对，直接从0.0.1 跳到 1.0.2，因为改动很大)
用正版 API（谷歌 彩云小译  Yandex Azure） + 有批量翻译 + 多支持了一个 .vtt 格式。
