### ISSUE TITLE
请求火山翻译的api接口

### ISSUE THREAD

**Issue by Florria2** [1c7/Translate-Subtitle-File#62]
请求火山翻译的api接口，火山翻译效果挺好的

**Comment by 1c7** [comment]
不行

**Comment by 1c7** [comment]
# 火山翻译的开发文档烂得一批，暂时不加。

## 字节跳动旗下的火山引擎，的确提供了机器翻译接口
https://www.volcengine.com/product/machine-translation
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1804755/225813005-aef603e7-052a-4212-8c82-3df93f0165ae.png">

## 但是它的开发文档烂得一批
https://www.volcengine.com/docs/4640/65067
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1804755/225813065-af842194-e0fa-4848-991e-f18dea2b00ff.png">

## 截止到2023-3-17 号周五
1. 我需要用 Node.js，但是目前 Node.js SDK 没有官方例子，https://github.com/volcengine/volc-sdk-nodejs/issues/3 还是好心人提供的 example。
2. 官方文档中没有提供 HTTP endpoint 地址，供其他编程语言（官方没有提供 SDK 的语言）进行使用。

## 工单回复截图
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1804755/225813519-46515859-f76f-4a3c-bc4f-5ff9cd0a4f4a.png">

**Comment by 1c7** [comment]
https://github.com/volcengine/volc-sdk-nodejs/issues/2

通过翻阅 Node.js SDK 的 Github issue。
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/1804755/225813712-bdab54ed-d1e6-4f63-a6c5-a2ecbf6fb5d5.png">

可以看到火山引擎根本不在乎他们的产品，稀烂的文档扔出来就算"发布"了。
除非开工单，Github 的 Issue 是根本不会回复的。

**Comment by 1c7** [comment]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1804755/225813943-ab6e04d2-d8ac-4c1d-9b2e-975b34d98633.png">

后续等我有空了会试一下这个，但是如果这个跑不通我就直接放弃掉

**Comment by 1c7** [comment]
总结成一句话：他们（火山引擎）不在乎客户。具体表现形式是：
1. 文档缺失的关键信息在开了工单之后只说一句『不支持，以文档为准』不针对具体问题进行回复，不说什么时候能解决这个具体问题（一周内？一个月内？）
2. Github Issue 完全不理睬

**Comment by 1c7** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1804755/225815629-467898b0-f49b-440d-bfec-3707265b1845.png">

我们已经接入了很多服务商了，不缺火山引擎一家

**Comment by 1c7** [comment]
## 跑通了，加上了

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1804755/225826466-ec9c563d-ec44-46e1-85bd-5fb8058ece5a.png">

拿了 Otto-J 的代码跑通了，干脆多写几行代码加到机翻助手里了。

**Comment by 1c7** [comment]
火山引擎加上去了，能使用了。
