### ISSUE TITLE
请问有没有加入OpenAI api的打算

### ISSUE THREAD

**Issue by 65887166** [1c7/Translate-Subtitle-File#69]
新用户可以试用3个月，后续好像也可以一直白嫖（

**Comment by 1c7** [comment]
之前试过 gpt-3.5-turbo，效果不太好。GPT-4 API 广泛可用之后可能再考虑加

**Comment by 65887166** [comment]
> 之前试过 gpt-3.5-turbo，效果不太好。GPT-4 API 广泛可用之后可能再考虑加

好的。其实还有个问题，OpenAI api和gpt-3.5的api是一回事吗

**Comment by 1c7** [comment]
是的。
OpenAI 的 API 如下：

https://platform.openai.com/docs/models
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1804755/236735135-8d025368-9641-4254-b005-4179d0ad41f1.png">

**Comment by 65887166** [comment]
明白了，谢谢。
