### ISSUE TITLE
百度翻译测试失败

### ISSUE THREAD

**Issue by nishino94** [1c7/Translate-Subtitle-File#76]
![IMG_20231031_225027](https://github.com/1c7/Translate-Subtitle-File/assets/64535086/9dae8977-9e7e-4c7c-ab8b-04e55e8d8bea)
百度翻译测试失败
ID和秘钥都没问题

**Comment by 1c7** [comment]
你好，网页版需要全程翻墙

**Comment by 1c7** [comment]
因为网页版的后端是谷歌云

**Comment by nishino94** [comment]
原来如此，感谢
