### ISSUE TITLE
可以对带标点符号的英文字幕做到更精确的翻译

### ISSUE THREAD

**Issue by xujin12368** [1c7/translate-subtitle-file#8]
如果能够区分标点符号，谷歌的机翻可以更加准确。

**Comment by 1c7** [comment]
我没明白你的意思。可以再展开讲讲？

**Comment by xujin12368** [comment]
> 我没明白你的意思。可以再展开讲讲？

我这边的字幕文件格式是这样的：
00:00:04,000 --> 00:00:08,000
So, as usual, before we dive and start playing with Unreal, we need to have some

3
00:00:08,000 --> 00:00:12,000
concept of what we're going to be doing. 
而使用你的软件是逐行翻译的，精度很低。
所以我想的是，根据字幕所含的标点符号，比如根据 ‘.' 句号做一个标记，将前面扫描到的语句组合成一句完整的话，然后再用谷歌进行翻译，导出的时候根据原英文语句的顺序排列就行。

**Comment by 1c7** [comment]
### 1 
这个软件的 0.0.1 版（就现在可以下载到的唯一一个版本）
是塞到5000字一次性翻译一批。（是5000还是500忘记了）

> 而使用你的软件是逐行翻译的，精度很低。

不存在一句一句翻译这种情况。

如果是一句句的，翻译一个文件起码30秒以上。
比如200多行字幕就有200多个 HTTP 请求，如果不并行（比如一次10个请求）
而是一个个的处理。差不多这么久

常规的 Crash Course 字幕大概有200多行字幕。
分批貌似会分成3，4批。拖进去点击"翻译"，大概2-4秒就可以了。

结论：是一大段一大段这样来的。不是一句一句的。

**Comment by 1c7** [comment]
目前的 master 分支是有另一个小哥贡献过代码的版本。
不是 0.0.1 版的代码。算是 0.0.2。但是我本地一直没法成功跑起来。就没法打包 0.0.2 然后发布出来

**Comment by 1c7** [comment]
如果没有其他问题，我就先关掉这个 issue 了，如果有后续讨论再 reopen。
目前看来讨论是结束了
