### ISSUE TITLE
网页版无法使用

### ISSUE THREAD

**Issue by Nothingtodoforma** [1c7/Translate-Subtitle-File#81]
挂梯子也不行

**Comment by 1c7** [comment]
<img width="1351" alt="image" src="https://github.com/1c7/Translate-Subtitle-File/assets/1804755/9ae1aa76-c6f3-448f-a825-b3fd0d8bcc23">

服务商要记得配置，我这边测百度好像没问题呀。你可以提供1-2个 .srt 字幕给我翻译试试

**Comment by 1c7** [comment]
你用的服务商是哪一个？浏览器是什么？

**Comment by horizon365** [comment]
用的百度，等了很久。firefox浏览器。
![图片](https://github.com/1c7/Translate-Subtitle-File/assets/17285011/b99def29-672e-44e7-9f16-3d73d18e8fe3)

**Comment by 1c7** [comment]
@horizon365 
您好，设置页面里"服务商"配置了吗？
可以加我 QQ 1003211008  把字幕文件发我，我来试试。
