### ISSUE TITLE
翻译分行问题

### ISSUE THREAD

**Issue by MAN-GOR** [1c7/Translate-Subtitle-File#82]
我是使用srt档翻译。
只翻译为「译文」时，当「-」号在开头能不能别合并为同一行翻译？就直接保持两行作翻译处理。
目前百度翻译有时候会删除了「-」号，导致看不明白。
测试过某一集原文总共有110个「-」号分行，但翻译后有20个被删除「-」号的。

例如：
\- Stop!
\- Baby. I'm sorry.

会转换为：
停止宝贝我很抱歉。

或：
\- Every day.
\- I'll let you go.

会转换为：
每一天我会让你走的。

**Comment by 1c7** [comment]
这个我好像没啥办法，换一家服务商试试
