### ISSUE TITLE
网页版原文在前，译文在后的功能不生效

### ISSUE THREAD

**Issue by SlayerYuwei** [1c7/Translate-Subtitle-File#83]
这是我的设置
![image](https://github.com/1c7/Translate-Subtitle-File/assets/117970747/089da1d8-4394-469e-a6ed-f3c276ae5fb0)
输出的字幕中，西语原文仍然在后面
![image](https://github.com/1c7/Translate-Subtitle-File/assets/117970747/f90a79b6-6be1-4919-a2b2-d38311167181)

**Comment by 1c7** [comment]
收到，问题已了解，之后我修一下

**Comment by 1c7** [comment]
您好，问题已修复，已触发部署，预计 15 分钟后生效。

**Comment by 1c7** [comment]
有其他的 bug 或者建议，欢迎随时告诉我

**Comment by 1c7** [comment]
<img width="1512" alt="image" src="https://github.com/1c7/Translate-Subtitle-File/assets/1804755/32b8f6ea-84e5-4854-8139-1dc5ce2f4db6">
生效了。
