### ISSUE TITLE
语音服务商讯飞显示错误码 26601, 错误描述: 非法应用信息|no appId info

### ISSUE THREAD

**Issue by maidang4** [1c7/Translate-Subtitle-File#84]
![讯飞错误](https://github.com/1c7/Translate-Subtitle-File/assets/76170249/8d39b291-88ce-422a-912c-68dc54b82d2b)

**Comment by 1c7** [comment]
您好，桌面版已经很久没有更新了，现在建议用网页版 https://tern.1c7.me/ （语音转文字功能在网页版里没有）
总之，感谢您的反馈。

**Comment by 1c7** [comment]
再说直白一点就是我上班比较忙，这个软件就更新得特别慢……

**Comment by maidang4** [comment]
好的，感谢你的付出，嘻嘻，生活愉快

**Comment by 1c7** [comment]
我暂时先把这个 issue 关掉。有后续消息可以再开新 issue
