### ISSUE TITLE
网页端报错，即使翻墙后

### ISSUE THREAD

**Issue by horizon365** [1c7/Translate-Subtitle-File#85]
![图片](https://github.com/1c7/Translate-Subtitle-File/assets/17285011/f3697fcf-f3b7-4163-8187-63723c85cdaf)
一直卡在第一句。

**Comment by 1c7** [comment]
右上角"设置"里，需要配置服务商（比如你用的是百度，那就要配置百度）

**Comment by 1c7** [comment]
<img width="1243" alt="image" src="https://github.com/1c7/Translate-Subtitle-File/assets/1804755/51413f9d-1522-484e-8a0d-025fe4e052f5">
<img width="1213" alt="image" src="https://github.com/1c7/Translate-Subtitle-File/assets/1804755/2e220969-8b85-4022-96fd-975fc27b1b57">

**Comment by horizon365** [comment]
哦，明白了。还以为网页有免费试用额度。原来是必须自己填
