### ISSUE TITLE
求potplayer的gpt扩展

### ISSUE THREAD

**Issue by sanxianianzi** [1c7/Translate-Subtitle-File#86]

**Comment by 1c7** [comment]
这好像跟我没啥关系呀，我用的 macOS 甚至都安装部了 PotPlayer

**Comment by sanxianianzi** [comment]
> 這好像跟我沒啥關係呀，我用的macOS甚至都無法安裝 PotPlayer（軟體不支援macOS平臺） 你許願許錯地方了。 我沒有 Windows 電腦（筆記型或台式都沒有）

抱歉許錯地方了 应该是gpt翻译
