### ISSUE TITLE
百度小语种翻译支持

### ISSUE THREAD

**Issue by BigMy** [1c7/Translate-Subtitle-File#89]
大佬，我想用百度api把目标语言翻译成小语种，不再默认的语言list里面，我如何操作才可以指定目标语种啊

**Comment by 1c7** [comment]
现在暂时不行，不可以自己输入语言 code

**Comment by 1c7** [comment]
https://fanyi-api.baidu.com/product/113

 我刚看了一眼，语种还是很多的，你需要哪个语言？

**Comment by 1c7** [comment]
你说一下你需要的语言，我可以很快的改一下网页版（不过网页版需要翻墙使用，因为后端是谷歌云）

**Comment by 1c7** [comment]
> 通用翻译API支持语种数已达 201种，完整列表如下。其中，对于常见语种列表内的语种，所有用户均可调用。对于非常见语种，仅企业已认证的尊享版用户可调用，未认证的非尊享版用户调用将返回错误。

https://fanyi-api.baidu.com/doc/21
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/52aaaa83-abce-47cc-88ac-74b46069369f">

**Comment by 1c7** [comment]
<img width="1369" alt="image" src="https://github.com/user-attachments/assets/5cc9a931-4529-4fd7-8b38-ff7ffa4d7602">

**Comment by BigMy** [comment]
> 你说一下你需要的语言，我可以很快的改一下网页版（不过网页版需要翻墙使用，因为后端是谷歌云）

马来语和印尼语！感谢，翻墙ok的

**Comment by 1c7** [comment]
字幕文件格式是 .srt .ass .vtt 都可以

**Comment by BigMy** [comment]
😂，没有诶，我们是要把国内采买版权的短剧投放到东南亚，是中文to东南亚语种，机翻后会有当地外包校准的

**Comment by BigMy** [comment]
没有，现在场景只有cn to id / cn to may😂

**Comment by 1c7** [comment]
对于非常见语种，仅企业已认证的尊享版用户可调用，未认证的非尊享版用户调用将返回错误。

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/a1909f6d-7924-44bf-af82-29031719c84f">


马来语和印尼语在百度这里属于非常见语种。
我自己没办法测试，因为我没有尊享版（要求企业认证）

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/dad34544-1435-49c9-a05b-266d6f9bcc9b">

**Comment by 1c7** [comment]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/8939a995-1c67-4036-9454-8aad8b7f8a2b">

线上生产环境 tern.1c7.me 我已经改好了，你如果有"尊享版"可以开始使用了。

**Comment by 1c7** [comment]
新的改动已部署上线，可以开始使用
