### ISSUE TITLE
【request】请求添加彩云小译

### ISSUE THREAD

**Issue by desireYY** [1c7/Translate-Subtitle-File#9]
彩云小译的翻译效果不错哦，希望可以添加
https://fanyi.caiyunapp.com/#/api

**Comment by 1c7** [comment]
收到，会看看

**Comment by 1c7** [comment]
@desireYY  打算加彩云小译，文档有数点不清楚的地方：
https://fanyi.caiyunapp.com/#/api

request_id 是什么意思？
![image](https://user-images.githubusercontent.com/1804755/70061928-1678c700-1620-11ea-89dd-19c35d8b20d5.png)

例子只给了 shell 和 Python 的。希望给一个清晰的列表。
解释下各个参数。而不是需要我看 Python 的代码来弄懂
