### ISSUE TITLE
批量翻译bug

### ISSUE THREAD

**Issue by SlayerYuwei** [1c7/Translate-Subtitle-File#91]
Chrome浏览器，用腾讯云和火山的API都试了，第一个字幕文件翻译完之后，不再继续翻译第二个字幕文件。
![image](https://github.com/user-attachments/assets/5acc2dbc-694e-4923-9e94-c86fb26feaf1)

**Comment by 1c7** [comment]
好的，感谢反馈，会尽快修复

**Comment by 1c7** [comment]
网页版此问题已修好，原因是代码里有个 bug，会调用桌面端的文件保存代码，但是这是网页端，自然就报错了，报错就阻止了它自动翻译下一个文件。

已修好，已上线。
