### ISSUE TITLE
请网页版也添加桌面版删掉末尾逗号和句号的功能

### ISSUE THREAD

**Issue by LeefenChen** [1c7/Translate-Subtitle-File#92]
旧版本里（字幕翻译成中文后，把逗号和句号换成一个空格）这个功能很好，看看网页版是不是也能实现添加一下，新版本这功能也没有了，彩云小译API也没了。
  个人感觉彩云小译翻译质量最高，我里面还有200万字数，我想如果网页版加上那功能以后只用网页版也行

**Comment by 1c7** [comment]
好的，收到

**Comment by 1c7** [comment]
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/cc98fd53-925e-4aa7-8239-2f2cc66f4b94" />

网页版已更新
（桌面版发布比较麻烦，我就不发布了，等有更大的改动再发动）
